LT-21078: Expose the string "<Not Sure>" externally.
sillsdev/liblcm pull request #249
Opened 2022-09-06 16:04 UTC by mark-sil

Expose the string "<Not Sure>" externally.

https://jira.sil.org/browse/LT-21078

2022-09-06 16:32 UTC, papeh requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/249)* status: all files reviewed, 2 unresolved discussions (waiting on @mark-sil)

___
*[`src/SIL.LCModel/StringsUtil.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/liblcm/249#-NBIbzWe3fgoRH0MEPrg:-NBIbzWe3fgoRH0MEPrh:bd90sc2) ([raw file](https://github.com/sillsdev/liblcm/blob/0b33700cc1f34c657aae4a767229ac7c8d20b496/src/SIL.LCModel/StringsUtil.cs#L9)):*
> ```Smalltalk
> namespace SIL.LCModel
> {
> 	public class StringsUtil
> ```

How about something like `LCModelStrings` or `LCModelPublicStrings` to avoid collisions
___
*[`src/SIL.LCModel/StringsUtil.cs` line 13 at r1](https://reviewable.io/reviews/sillsdev/liblcm/249#-NBIcG_vDT1V3cw3-Buj:-NBIcG_vDT1V3cw3-Buk:b-iobj69) ([raw file](https://github.com/sillsdev/liblcm/blob/0b33700cc1f34c657aae4a767229ac7c8d20b496/src/SIL.LCModel/StringsUtil.cs#L13)):*
> ```Smalltalk
> 		/// ------------------------------------------------------------------------------------
> 		/// <summary>
> 		/// Expose the "<Not Sure>" string to external modules.
> ```

How about `<inheritdoc cref="Strings.ksNotSure"/>`


<!-- Sent from Reviewable.io -->

2022-09-06 17:16 UTC, mark-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/249)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @papeh)

___
*[`src/SIL.LCModel/StringsUtil.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/liblcm/249#-NBIbzWe3fgoRH0MEPrg:-NBInHpX0zAfsuSZX6TC:b-896fix) ([raw file](https://github.com/sillsdev/liblcm/blob/0b33700cc1f34c657aae4a767229ac7c8d20b496/src/SIL.LCModel/StringsUtil.cs#L9)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

How about something like `LCModelStrings` or `LCModelPublicStrings` to avoid collisions
</blockquote></details>

Done.
___
*[`src/SIL.LCModel/StringsUtil.cs` line 13 at r1](https://reviewable.io/reviews/sillsdev/liblcm/249#-NBIcG_vDT1V3cw3-Buj:-NBInHXO3zzdk5DloQwc:b-896fix) ([raw file](https://github.com/sillsdev/liblcm/blob/0b33700cc1f34c657aae4a767229ac7c8d20b496/src/SIL.LCModel/StringsUtil.cs#L13)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

How about `<inheritdoc cref="Strings.ksNotSure"/>`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-06 18:23 UTC, papeh approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/249)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mark-sil)



<!-- Sent from Reviewable.io -->

2022-09-06 18:23 UTC, merged

2022-09-07 07:15 UTC, ermshiperete commented
This deserves a +semver:minor and an entry in `CHANGELOG.md`...